# SEO
title: PepperCord
author: regulad

# Jekyll
remote_theme: regulad/crust-tastic

# Plugins
plugins:
  - github-pages
  - jekyll-redirect-from

# crust-tastic
crust_tastic:
  gtag: G-M7M093KQ3H
  github: true
