services:
  mongo:
    image: "mongo:5"
    ports:
      - "27017:27017/tcp"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "128M"
    hostname: "mongo"
    restart: "always"
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - backend
    volumes:
      - "db:/data/db"
  redis:
    image: "redis:8.4-alpine3.22"
    ports:
      - "6379:6379/tcp"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.01"
          memory: "64M"
    hostname: "redis"
    restart: "always"
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - backend
    volumes:
      - redis:/data
  peppercord:
    image: "ghcr.io/regulad/peppercord:latest"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
        reservations:
          cpus: "1"
          memory: "1G"
    dns:
      # Discord uses rapidly-reconfigured domain names to direct traffic to its WS and RTC gateways.
      # With PepperCord in production, I've had the best experience with the Google DNS servers
      # I suspect this is because Discord uses GCP and updates propagate the fastest internally.
      - "8.8.8.8"
      - "8.8.4.4"
      # These will go unused with the default configuration, unless the daemon is configured to allocate IPv6 subnets to all docker networks
      - "2001:4860:4860::8888"
      - "2001:4860:4860::8844"
    env_file: ".env"
    build: .
    restart: "restart"
    read_only: true
    depends_on:
      - "mongo"
      - "redis"
    tmpfs:
      - /tmp
    networks:
      - backend
      - frontend
    volumes:
      - "/etc/default/locale:/etc/default/locale:ro"
      - "/usr/share/locale:/usr/share/locale:ro"
      - "/usr/lib/locale:/usr/lib/locale:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels: [ "com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}" ]
  watchtower:
    # Auto-updating is a necessary evil due to Discord's reluctance to maintain older APIs
    image: "containrrr/watchtower:latest"
    restart: "restart"
    read_only: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DOCKER_API_VERSION: "1.52"
    tmpfs:
      - "/tmp"
      - "/var/run"
    command:
      - "--scope"
      - "${WATCHTOWER_SCOPE}"
      - "--cleanup"
      - "peppercord"
    labels: [ "com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}" ]
volumes:
  db:
  redis:
networks:
  backend:
    internal: true  # databases are fine without internet
  frontend:
    internal: false
